language: r
warnings_are_errors: true
cache: packages
env:
  global:
    secure: YzaRM1HxmpK4UkMBCJxcTOA+TILyPqFVqbdvZEaDNQmc6mj7usLYvnnmlZ+z47a44dKXDq8jNn6lzWyHknf4Vy065xEklaWOZfeQ6SuGHc/QviJUNnXNMEoqgvWitH9aZmNkuXxXyDhkWFezh/Nbfyyijuq15LQ7ru28AZK68jKTRbqK3zJV3nUc5WVwKs5dRRfve+uoYIZsPpO36l7VzCSNyJHCRhPQWyf9ehTTBDKPPBza8KrxwPiSlWowKnb2rSN9jVxb8C7RSCj0iu9FD++Cnaf20e2p4xr5REVdrqWtVjgMQxdIQfcR+Vf0js3O3aXxRA/KMA6XyztAlK7rqgM1zqkkBn/S7To2bdVZjoRwJtPI2/N7uCSxQqji90B3z+ayMWl61ofCSpi0bD8GH9YxAKNk+FaV0R5eAYBQAyd4YbZPQwlk3FoO+i5xqP51lCa2IF7tRg4TX7MtQeOykewLw2mJb1GTtH+BgnsV1nrl6vDJAHgWZfWmQCt1/mkBg6jpiibFgqfRtiaMyb+8/xJH/QgwsuTWJteEVm/qnWQ8jZev3U4/QrUk4hnNBNDZKu9eqBZqGit810h8cta0QDfrQceTBwIi0Xtt981sAj0dNmmsb1rCcnlHM+KeKJLgKQc37pVSrvettmTCO/mFbJVPT17ZHufCyROPnxiSoh0=
